services:
  db:
    image: mysql:8.0.44 
    container_name: blog_mysql_container
    restart: always
    environment:
      MYSQL_DATABASE: 'blog_db' 
      MYSQL_ROOT_PASSWORD: 'rootpass'
    ports:
      - '3309:3306'
    volumes:
     
      - ./banco.sql:/docker-entrypoint-initdb.d/banco.sql